[version]
current = "0.2.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<pre>(a|b)\d+)?
'''

[git]
message_template = ":bookmark: Bump to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "pyproject.toml"
version_template = "{major}.{minor}.{patch}{pre}"

[[file]]
src = "docs/conf.py"
version_template = "{major}.{minor}.{patch}{pre}"

[[field]]
name = "pre"
default = ""
