[tox]
envlist =
    py{310,311,312,313,314}
    ruff
    docs
    mypy
skip_missing_interpreters = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
extras = dev
commands =
  py.test tests \
   --cov=ape_pie --cov-report xml:reports/coverage-{envname}.xml \
   {posargs}

[testenv:mypy]
basepython = python
extras = types
skipsdist = True
commands = mypy src

[testenv:ruff]
extras = dev
skipsdist = True
commands =
    ruff check --output-format=github .
    ruff format --check

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    dev
    docs
commands=
    py.test check_sphinx.py -v \
    --tb=auto \
    {posargs}
